export const QUERY_FILTER_CATEGORY = 'QUERY_FILTER_CATEGORY';
export const QUERY_FILTER_TAG = 'QUERY_FILTER_TAG';
export const QUERY_FILTER_SEARCH = 'QUERY_FILTER_SEARCH';
export const QUERY_FILTER_CLEAN = 'QUERY_FILTER_CLEAN';
